In [2]:
import pandas as pd 
import numpy as np 
import random

# random.randint() VS np.random.randint()

In [3]:
[random.randint(0,1) for i in range(10)] #在[0，1]中二选一形成bool变量

[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]

In [14]:
[random.randint(1,3) for i in range(10)] 

[3, 3, 2, 2, 1, 3, 2, 2, 1, 1]

In [10]:
[np.random.randint(0,1,size=1) for i in range(10)]

[array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0])]

In [8]:
[np.random.randint(0,4,size=3) for i in range(10)]#在[0,1,2，3]中四个取出三个

[array([3, 2, 2]),
 array([3, 2, 2]),
 array([3, 2, 1]),
 array([1, 0, 3]),
 array([2, 0, 0]),
 array([0, 0, 1]),
 array([3, 0, 0]),
 array([1, 0, 1]),
 array([2, 1, 3]),
 array([2, 2, 3])]